import pygame
from player import Player
from item import Item

# Code generated by ChatGPT and edited by Liliana Dhaliwal
# Some code written by Liliana Dhaliwal
# Comments by Liliana Dhaliwal
class Game:
    def __init__(self):
        pygame.init()
        
        self.screen_width = 800
        self.screen_height = 600

        self.screen = pygame.display.set_mode((self.screen_width, self.screen_height))
        pygame.display.set_caption("Catch the Item Game")

        self.clock = pygame.time.Clock()
        self.running = True

        self.player = Player(self.screen_width, self.screen_height)
        self.items = pygame.sprite.Group()

        for i in range(10):
            self.items.add(Item(self.screen_width, self.screen_height))

        self.score = 0

    def run(self):
        while self.running:
            self.handle_events()
            self.update()
            self.render()

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                self.running = False

        keys = pygame.key.get_pressed()
        self.player.update(keys)

    def update(self):
        # Updates the items' states and positions
        for item in self.items:
            item.update()

        collided_items = pygame.sprite.spritecollide(self.player, self.items, False)

        for item in collided_items:
            item.update("caught")
            self.score += 1
        
        ##if self.score >= 5:
            ##for item in self.items:
                ##item.update("run away")

    # Draws the game
    def render(self):
        self.screen.fill((255, 255, 255))
        pygame.draw.rect(self.screen, (0, 255, 0), self.player.rect)

        for item in self.items:
            if item.visible == True:
                pygame.draw.rect(self.screen, (255, 0, 0), item.rect)

        pygame.display.flip()
        self.clock.tick(30)

    def cleanup(self):
        pygame.quit()

if __name__ == "__main__":
    game = Game()
    game.run()
    game.cleanup()
