import pygame
import random

# Code generated by ChatGPT and edited by Liliana Dhaliwal
# Comments by Liliana Dhaliwal
class Item(pygame.sprite.Sprite):
    def __init__(self, screen_width, screen_height):
        super().__init__()

        # Intializes the item
        self.image = pygame.Surface((30, 30))
        self.image.fill((255, 0, 0))
        self.rect = self.image.get_rect()
        self.rect.x = random.randint(0, screen_width - 30)
        self.rect.y = random.randint(0, screen_height - 30)

        self.speed = 3
        self.direction = random.choice([-1, 1])  

    def update(self):
        # Moves the item horizontally
        self.rect.x += self.speed * self.direction

        # Changes the item's direction if it hits the window boundaries
        if self.rect.x <= 0 or self.rect.x >= 800 - 30:
            self.direction *= -1

        # Moves the item vertically
        self.rect.y += self.speed * self.direction

        # Changes the item's direction if it hits the window boundaries
        if self.rect.y <= 0 or self.rect.y >= 600 - 30:
            self.direction *= -1
